### ISSUE TITLE
Jump to editors/review page

### ISSUE THREAD

**Issue by Noitidart** [wagnerand/addon-review-helper#1]
Fantastic, can we submit PR which puts a toolbar button. On click, if the current page is the "listing" page it will jump it to the editor/review page

For instance if I am viewing this page:
https://addons.mozilla.org/en-US/firefox/addon/gnotifier/

Clicking the toolbar button will jump it to:
https://addons.mozilla.org/en-US/editors/review/gnotifier

Would you prefer something other then toolbarbutton? Like should i add the item to context menu only when the current page is the listing page?

**Comment by wagnerand** [comment]
This is already a feature of https://addons.mozilla.org/en-US/firefox/addon/amo-admin-assistant/

**Comment by Noitidart** [comment]
Oh sweet thanks!
