### ISSUE TITLE
Does not list "older" entries

### ISSUE THREAD

**Issue by Noitidart** [wagnerand/addon-review-helper#3]
For addons with tons of entires, the "older" entries are hidden until we click the "Older" link. The addon is not listing them. It would be a nice enhancement if it listed the older ones.

Example - https://addons.mozilla.org/en-US/editors/review/video-downloadhelper

**Comment by wagnerand** [comment]
Yeah, that would be nice, but it requires even more screen-scraping review pages. I don't want to do that. Maybe we will get that information once the editor tools get an API.

**Comment by wagnerand** [comment]
I'm going to close this and we will get back to it once the reviewer tools have a proper API.
